### PR TITLE
Added the Improvement Request Template

### LINKED ISSUE #483: Add Improvement Request Template
On [this page](https://github.com/microsoft/qsharp-runtime/issues/new/choose) add a new template - **Improvement Request**, in order to file the requests for improvement. E.g. [coding style improvement](https://github.com/microsoft/qsharp-runtime/issues/482).
Add a new .md file [here](https://github.com/microsoft/qsharp-runtime/tree/main/.github/ISSUE_TEMPLATE).

### PR DESCRIPTION
**Pull request by kuzminrobin**
Resolves #483

### CODE REVIEW

**Comment by irinayat-MS** [comment]
With this addition, the list of issue templates will look like this:

*Bug report*
Create a report to help us improve

*Feature request*
Suggest an idea for this project

*Improvement request*
Suggest an improvement for this project

I'm not sure I can delineate between improvement for this project versus an idea for this project, and a bug report to help us improve versus an improvement to help us improve. I suspect, our external contributors will be similarly confused. If the purpose of this new category is to address the engineering debt of the codebase, maybe, call it like that?

**Review by bettinaheim — APPROVED** [review]

**Comment by kuzminrobin** [comment]
> I'm not sure I can delineate between improvement for this project versus an idea for this project, and a bug report to help us improve versus an improvement to help us improve. I suspect, our external contributors will be similarly confused. If the purpose of this new category is to address the engineering debt of the codebase, maybe, call it like that?

When I was asked to file an issue for the item 1 in #482, I (not thinking much) opened the issue as a _bug_ (but I felt that reporting it as a _bug_ was somewhat wrong thing to do, it was not a _bug_/defect).  
Then, when reporting the #484, I decided to open it as a _feature_ (and again I felt that the word _feature_ did not reflect the reality, because I'm not asking for a functionality that didn't exist before). I felt a need for a request for _improvement_ of the existing functionality (not _fixing_, not _adding_ the functionality). That is why I filed that #483 (Add Improvement Request Template).  

But if adding the Improvement Request Template causes a confusion or redundancy, then I'm OK leaving the things as they are (and cancel this PR).  Just let me know what the majority would prefer.

Looks like the perception of this Improvement Request (as opposed to the Bug Report and Feature Request) is somewhat subjective for either side, and depends on how people interpret the Feature Request- either as a new functionality request or as an improvement request in a broad sense.

Please let me know your preference: 
* to add the Improvement Request Template
* to _not_ add the Improvement Request Template
* other

**Comment by irinayat-MS** [comment]
I'd vote for either doing nothing or adding a new issue templates that covers cleanups, refactors, toolchain changes, technical debt and so on, that is, *non-customer facing* maintenance of the codebase.

```
name: Maintenance request
description: Create a request to improve quality of the codebase or the tooling
```

**Comment by kuzminrobin** [comment]
>  or adding a new issue template that covers ...

Looks like a good idea to me. @bettinaheim, what do you think?

**Review by irinayat-MS — APPROVED** [review]
lgtm
Thank you!

**Pull request merged**
