### PR TITLE
Prevent circular references when serializing Qubit values.

### PR DESCRIPTION
**Pull request by cgranade**
This PR adds the `[JsonIgnore]` attribute to `Qubit.Value` in the C# runtime, preventing circular references when serializing values of type `Qubit`. This in turn allows for `DisplayableUnitaryOperator` from Microsoft.Quantum.Standard and Microsoft.Quantum.Standard.Visualization to be sent from the IQ# kernel through to Python hosts correctly, such that Python host programs can capture operations dumped from Q# programs.

### CODE REVIEW

**Comment by bettinaheim** [comment]
@cgranade Does this need to go into main urgently? If not, could we please first pull in the simulator feature before having other merges to the runtime.

**Comment by cgranade** [comment]
Not urgent, no. Just a small bugfix I found while prototyping some Python features.

**Comment by cgranade** [comment]
image

Sigh, another CI failure due to the simulator crashing.

**Comment by swernli** [comment]
Sigh indeed. We did have a potential fix for this, but it's tied up with #710. Perhaps it's worth pulling that part of the change out into its own PR?

**Comment by cgranade** [comment]
@bettinaheim, @swernli: Now that `main` is open again, would it be possible to merge this fix in for the July release? Thank you!

**Comment by swernli** [comment]
Closing as out of date, as there is now a workaround in IQ#.

**Pull request closed without merging**
