### PR TITLE
Update Simulator default random seed

### PR DESCRIPTION
**Pull request by swernli**
This updates the default seed used by the simulator when initializing the random number generator used within the wave function. Previously it used `std::clock()` which is time since process start, but that is implementation and platform dependent (see https://en.cppreference.com/w/cpp/chrono/c/clock). This is changed to instead use current time, and was tested to show sufficient randomness even with rapid repeated invocation.

### CODE REVIEW

**Review by cesarzc — APPROVED** [review]
LGTM.

Interesting bug fix :)

**Review by kuzminrobin — APPROVED** [review]

**Review by idavis — CHANGES_REQUESTED** [review]
My historical assumptions are that seed is always set to current instant to create "random" behavior. But that if someone wants to create determinism, then, and only then they override

**Comment by swernli** [comment]
@idavis That's a good point... The current behavior is the other way around. I think the right fix to get safe-by-default randomness is to replace the use of `std::clock()` in the simulator wave function itself. I switch to that pattern.

**Comment by kuzminrobin** [comment]
What do you guys think about this PR - #780?
It allows the user to choose whether the random sequence will be deterministic or not.

**Comment by swernli** [comment]
@kuzminrobin I think that PR makes sense, and would even be reasonable to include along with this one. After the change, this one is more about making sure the native fullstate simulator is safe-by-default. But since the C# wrapper already explicitly sets the seed, there is nothing wrong with the QIR wrapper doing the same. Having it be parametrizable is also a step toward addressing feedback we've received about wanting a way to make the simulator deterministic for testing (see https://github.com/microsoft/qsharp-runtime/issues/187#issuecomment-715626082 for example).

**Review by idavis — APPROVED** [review]

**Pull request merged**
