### PR TITLE
Updated Version Numbers

### PR DESCRIPTION
**Pull request by ScottCarda-MS**
The old version number seemed to reference data types that are not available in the main branch of the compiler repo, but rather a not-yet merged in feature branch. The new version number references a package made from the main branch of the compiler repo.

### CODE REVIEW

**Review by swernli — CHANGES_REQUESTED** [review]
This won’t be able to merge. We are in an awkward state where QIR support is in main here, including tests that are part of the build pipeline, while the required changes to the compiler to make QIR generations work are in a working branch of Qsharp-compiler. We need to get those changes merged into main in compiler, but to keep runtime building we need to use those packages here.

**Comment by ScottCarda-MS** [comment]
> This won’t be able to merge. We are in an awkward state where QIR support is in main here, including tests that are part of the build pipeline, while the required changes to the compiler to make QIR generations work are in a working branch of Qsharp-compiler. We need to get those changes merged into main in compiler, but to keep runtime building we need to use those packages here.

How long before the main branch on the compiler repo has the data types needed to work with this?

**Comment by ScottCarda-MS** [comment]
> > This won’t be able to merge. We are in an awkward state where QIR support is in main here, including tests that are part of the build pipeline, while the required changes to the compiler to make QIR generations work are in a working branch of Qsharp-compiler. We need to get those changes merged into main in compiler, but to keep runtime building we need to use those packages here.
> 
> How long before the main branch on the compiler repo has the data types needed to work with this?

And can those tests be marked as Skip until that happens?

**Comment by ScottCarda-MS** [comment]
> > > This won’t be able to merge. We are in an awkward state where QIR support is in main here, including tests that are part of the build pipeline, while the required changes to the compiler to make QIR generations work are in a working branch of Qsharp-compiler. We need to get those changes merged into main in compiler, but to keep runtime building we need to use those packages here.
> > 
> > 
> > How long before the main branch on the compiler repo has the data types needed to work with this?
> 
> And can those tests be marked as Skip until that happens?

It sounds like there will be some time put aside next week to address this and try to get the main of the compiler repo to agree with the main of the runtime repo. If so, this PR may not be needed.

**Comment by swernli** [comment]
In the meantime, if you are blocked, you can try `0.15.2102129941-alpha`, which should hopefully have the changes you need in it.

**Comment by ScottCarda-MS** [comment]
This was addressed in the compiler PR here (https://github.com/microsoft/qsharp-compiler/pull/893). With this the main branch of the compiler is now compatible with the main branch of this repo. This makes this PR unnecessary now.

**Pull request closed without merging**
